# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-minor-days: 7
      semver-patch-days: 7
    eslint:
      patterns:
        - "@eslint/*"
        - "eslint"
        - "typescript-eslint"
      applies-to: version-updates
