name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'New Presets'
    labels:
      - 'new-preset'
  - title: 'New and Changed Fields'
    labels:
      - 'field'
      - 'new-field'
      - 'new-value'
  - title: 'Changed Presets'
    labels:
      - 'add-field'
      - 'new-icon'
      - 'new-label'
  - title: 'Regional Presets and Fields'
    labels:
      - 'regional'
  - title: 'Deprecated Tags'
    labels:
      - 'deprecating'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation and Other Changes'
    label: 'ci'
    label: 'github-actions'
    label: 'documentation'
    label: 'new-category'
    label: 'javascript'
    label: 'schema-builder'
    label: 'schema'
  - title: 'Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
change-template: '* $TITLE (#$NUMBER, thanks @$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: minor
template: $CHANGES